# https://jupyter-docker-stacks.readthedocs.io/en/latest/
# https://hub.docker.com/r/bitnami/spark/
services:
  jupyter-pyspark-notebook:
    build: ./docker/jupyter-pyspark
    environment:
      NOTEBOOK_ARGS: --NotebookApp.token=''
    ports:
      - '8888:8888'
      - '4040-4060:4040-4060'
    volumes:
      - ./data:/opt/workspace
      - ./notebooks:/home/jovyan/work/notebooks
      - ./pyscripts:/home/jovyan/work/pyscripts
      - ./spark.conf:/usr/local/spark/conf/spark-defaults.conf
  postgresql-world-db:
    build: ./docker/postgresql-world-db
    ports:
      - 5432:5432
  data-producer:
    build: ./docker/data-producer
    depends_on:
      - kafka-broker
    environment:
      - KAFKA_HOST=kafka-broker:29092
      - KAFKA_TOPIC=web-events
      - SIMULATION_TIME_SECONDS=86400
      - USER_POOL_SIZE=100
      - SESSIONS_PER_DAY=100000
    volumes:
      - ./data:/opt/workspace
  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka-broker:
    image: docker.io/confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1